export const GET_NEW_GIF = "GET_NEW_GIF";
export const SPOTIFY_LOGIN_AUTH = "SPOTIFY_LOGIN_AUTH";
export const SPOTIFY_SET_PLAYLIST = "SPOTIFY_SET_PLAYLIST";
export const SPOTIFY_SET_CURRENT_TRACKS = "SPOTIFY_SET_CURRENT_TRACKS";
export const SPOTIFY_SET_CURRENTLY_PLAYING = "SPOTIFY_SET_CURRENTLY_PLAYING";
